name: lezzet_duraklari
description: "Lezzet Durakları uygulaması, çevrenizdeki lezzetli yerleri keşfetmenizi sağlar."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  dio: ^5.7.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0
  envied: ^0.5.4+1
  get_it: ^8.0.0
  injectable: ^2.5.0
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.3.2
  dartz: ^0.10.1
  formz: ^0.7.0
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  go_router: ^14.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2
  envied_generator: ^0.5.4+1
  injectable_generator: ^2.6.2
  flutter_gen_runner: ^5.8.0
  flutter_native_splash: ^2.4.1


flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/logos/
    - assets/icons/

flutter_gen:
  output: lib/core/gen/
  integrations:
    flutter_svg: true
